name: dygraphs_dart
description: A Dart wrapper for dygraphs.com js library
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: '>=1.0.0 <2.0.0'
